use crate::ast::*;
use std::collections::{HashMap, HashSet};

pub struct CodeGenerator {
    pub imported_crates: Vec<String>,
    scopes: Vec<HashSet<String>>,
    type_env: HashMap<String, TypeAnnotation>,
}

impl CodeGenerator {
    pub fn new() -> Self {
        Self {
            imported_crates: Vec::new(),
            scopes: vec![HashSet::new()],
            type_env: HashMap::new(),
        }
    }

    fn push_scope(&mut self) {
        self.scopes.push(HashSet::new());
    }

    fn pop_scope(&mut self) {
        if let Some(scope) = self.scopes.pop() {
            for var in scope {
                self.type_env.remove(&var);
            }
        }
    }

    fn declare_var(&mut self, name: &str, ty: TypeAnnotation) {
        if let Some(scope) = self.scopes.last_mut() {
            scope.insert(name.to_string());
        }
        self.type_env.insert(name.to_string(), ty);
    }

    fn is_declared(&self, name: &str) -> bool {
        for scope in self.scopes.iter().rev() {
            if scope.contains(name) {
                return true;
            }
        }
        false
    }

    fn get_var_type(&self, name: &str) -> TypeAnnotation {
        self.type_env
            .get(name)
            .cloned()
            .unwrap_or(TypeAnnotation::Dynamic)
    }

    pub fn generate(&mut self, program: &Program) -> String {
        let mut out = String::new();

        out.push_str("// Generated by Lingo Compiler (lingoc)\n");
        out.push_str("#![allow(unused_variables, unused_mut, dead_code, unused_parens)]\n");
        out.push_str("use lingo_runtime::{Value, lingo_print, lingo_println};\n\n");

        for stmt in &program.statements {
            out.push_str(&self.gen_stmt(stmt, 0));
            out.push('\n');
        }

        out
    }

    fn gen_stmt(&mut self, stmt: &Stmt, indent: usize) -> String {
        let pad = "    ".repeat(indent);
        match stmt {
            Stmt::Import { module, alias } => {
                let mod_path = module.join("::");
                if let Some(first) = module.first() {
                    if first != "std" && !self.imported_crates.contains(first) {
                        self.imported_crates.push(first.clone());
                    }
                }
                if let Some(al) = alias {
                    format!("{}use {} as {};\n", pad, mod_path, al)
                } else {
                    format!("{}use {};\n", pad, mod_path)
                }
            }

            Stmt::Def {
                name,
                params,
                return_type,
                body,
            } => {
                let mut s = String::new();
                let is_main = name == "main";

                self.push_scope();

                let ret_str = if is_main {
                    "".to_string()
                } else {
                    match return_type {
                        TypeAnnotation::Dynamic => " -> Value".to_string(),
                        _ => format!(" -> {}", self.gen_type(return_type)),
                    }
                };

                let param_strs: Vec<String> = params
                    .iter()
                    .map(|p| {
                        self.declare_var(&p.name, p.ty.clone());
                        if p.is_self {
                            "&mut self".to_string()
                        } else {
                            format!("{}: {}", p.name, self.gen_type(&p.ty))
                        }
                    })
                    .collect();

                s.push_str(&format!(
                    "{}pub fn {}({}){} {{\n",
                    pad,
                    name,
                    param_strs.join(", "),
                    ret_str
                ));

                for b_stmt in body {
                    s.push_str(&self.gen_stmt(b_stmt, indent + 1));
                }

                self.pop_scope();

                s.push_str(&format!("{}}}\n", pad));
                s
            }

            Stmt::Class { name, fields } => {
                let mut s = String::new();
                s.push_str(&format!("{}#[derive(Clone, Debug)]\n", pad));
                s.push_str(&format!("{}pub struct {} {{\n", pad, name));
                for (fname, fty) in fields {
                    s.push_str(&format!(
                        "{}    pub {}: {},\n",
                        pad,
                        fname,
                        self.gen_type(fty)
                    ));
                }
                s.push_str(&format!("{}}}\n", pad));
                s
            }

            Stmt::Protocol { name, methods } => {
                let mut s = String::new();
                s.push_str(&format!("{}pub trait {} {{\n", pad, name));
                for (mname, params, ret) in methods {
                    let param_strs: Vec<String> = params
                        .iter()
                        .map(|p| {
                            if p.is_self {
                                "&mut self".to_string()
                            } else {
                                format!("{}: {}", p.name, self.gen_type(&p.ty))
                            }
                        })
                        .collect();

                    let ret_str = match ret {
                        TypeAnnotation::Dynamic => " -> Value".to_string(),
                        _ => format!(" -> {}", self.gen_type(ret)),
                    };

                    s.push_str(&format!(
                        "{}    fn {}({}){};\n",
                        pad,
                        mname,
                        param_strs.join(", "),
                        ret_str
                    ));
                }
                s.push_str(&format!("{}}}\n", pad));
                s
            }

            Stmt::Impl {
                target,
                protocol,
                methods,
            } => {
                let mut s = String::new();
                if let Some(proto) = protocol {
                    s.push_str(&format!("{}impl {} for {} {{\n", pad, proto, target));
                } else {
                    s.push_str(&format!("{}impl {} {{\n", pad, target));
                }

                for m in methods {
                    s.push_str(&self.gen_stmt(m, indent + 1));
                }

                s.push_str(&format!("{}}}\n", pad));
                s
            }

            Stmt::Let {
                name,
                is_mut,
                ty,
                init,
            } => {
                let actual_ty = if matches!(ty, TypeAnnotation::Dynamic) {
                    if let Expr::StructInit { ref name, .. } = init {
                        TypeAnnotation::Named(name.clone())
                    } else {
                        TypeAnnotation::Dynamic
                    }
                } else {
                    ty.clone()
                };

                self.declare_var(name, actual_ty.clone());
                let mut_kw = if *is_mut { "mut " } else { "" };
                let is_dyn = matches!(actual_ty, TypeAnnotation::Dynamic);
                let ty_str = if is_dyn {
                    "Value".to_string()
                } else {
                    self.gen_type(&actual_ty)
                };
                let init_str = self.gen_expr(init, is_dyn);
                format!(
                    "{}let {}{}: {} = {};\n",
                    pad, mut_kw, name, ty_str, init_str
                )
            }

            Stmt::Assignment { target, value } => {
                let value_str = self.gen_expr(value, true);
                if let Expr::Var(var_name) = target {
                    if !self.is_declared(var_name) {
                        self.declare_var(var_name, TypeAnnotation::Dynamic);
                        return format!("{}let mut {} = {};\n", pad, var_name, value_str);
                    } else {
                        return format!("{}{} = {};\n", pad, var_name, value_str);
                    }
                }
                let target_str = self.gen_expr(target, false);
                format!("{}{} = {};\n", pad, target_str, value_str)
            }

            Stmt::If {
                condition,
                then_branch,
                elif_branches,
                else_branch,
            } => {
                let mut s = String::new();
                let cond_str = self.gen_expr(condition, false);
                s.push_str(&format!("{}if ({}).is_truthy() {{\n", pad, cond_str));

                self.push_scope();
                for st in then_branch {
                    s.push_str(&self.gen_stmt(st, indent + 1));
                }
                self.pop_scope();
                s.push_str(&format!("{}}}", pad));

                for (elif_cond, elif_body) in elif_branches {
                    let elif_cond_str = self.gen_expr(elif_cond, false);
                    s.push_str(&format!(
                        " else if ({}).is_truthy() {{\n",
                        elif_cond_str
                    ));
                    self.push_scope();
                    for st in elif_body {
                        s.push_str(&self.gen_stmt(st, indent + 1));
                    }
                    self.pop_scope();
                    s.push_str(&format!("{}}}", pad));
                }

                if let Some(else_b) = else_branch {
                    s.push_str(" else {\n");
                    self.push_scope();
                    for st in else_b {
                        s.push_str(&self.gen_stmt(st, indent + 1));
                    }
                    self.pop_scope();
                    s.push_str(&format!("{}}}\n", pad));
                } else {
                    s.push_str("\n");
                }
                s
            }

            Stmt::While { condition, body } => {
                let mut s = String::new();
                let cond_str = self.gen_expr(condition, false);
                s.push_str(&format!("{}while ({}).is_truthy() {{\n", pad, cond_str));

                self.push_scope();
                for st in body {
                    s.push_str(&self.gen_stmt(st, indent + 1));
                }
                self.pop_scope();

                s.push_str(&format!("{}}}\n", pad));
                s
            }

            Stmt::For { var, iterable, body } => {
                let mut s = String::new();
                let iter_str = self.gen_expr(iterable, false);
                s.push_str(&format!("{}for {} in {} {{\n", pad, var, iter_str));

                self.push_scope();
                self.declare_var(var, TypeAnnotation::Dynamic);
                for st in body {
                    s.push_str(&self.gen_stmt(st, indent + 1));
                }
                self.pop_scope();

                s.push_str(&format!("{}}}\n", pad));
                s
            }

            Stmt::Return(expr_opt) => {
                if let Some(expr) = expr_opt {
                    format!("{}return {};\n", pad, self.gen_expr(expr, true))
                } else {
                    format!("{}return Value::Nil;\n", pad)
                }
            }

            Stmt::ExprStmt(expr) => {
                format!("{}{};\n", pad, self.gen_expr(expr, false))
            }
        }
    }

    fn gen_type(&self, ty: &TypeAnnotation) -> String {
        match ty {
            TypeAnnotation::Dynamic => "Value".to_string(),
            TypeAnnotation::Named(n) => n.clone(),
            TypeAnnotation::Reference { mutable, inner } => {
                let mut_kw = if *mutable { "mut " } else { "" };
                format!("&{}{}", mut_kw, self.gen_type(inner))
            }
        }
    }

    fn gen_expr(&mut self, expr: &Expr, force_value: bool) -> String {
        match expr {
            Expr::Literal(lit) => match lit {
                LiteralValue::Nil => "Value::Nil".to_string(),
                LiteralValue::Bool(b) => {
                    if force_value {
                        format!("Value::Bool({})", b)
                    } else {
                        b.to_string()
                    }
                }
                LiteralValue::Int(i) => {
                    if force_value {
                        format!("Value::Int({})", i)
                    } else {
                        i.to_string()
                    }
                }
                LiteralValue::Float(f) => {
                    if force_value {
                        format!("Value::Float({:?})", f)
                    } else {
                        format!("{:?}", f)
                    }
                }
                LiteralValue::Str(s) => {
                    if force_value {
                        format!("Value::Str({:?}.to_string())", s)
                    } else {
                        format!("{:?}.to_string()", s)
                    }
                }
            },

            Expr::Var(name) => {
                let ty = self.get_var_type(name);
                if force_value && matches!(ty, TypeAnnotation::Dynamic) {
                    format!("{}.clone()", name)
                } else {
                    name.clone()
                }
            }

            Expr::Binary { left, op, right } => {
                let left_is_static = if let Expr::Var(v) = left.as_ref() {
                    !matches!(self.get_var_type(v), TypeAnnotation::Dynamic)
                } else if let Expr::FieldAccess { object, .. } = left.as_ref() {
                    if let Expr::Var(v) = object.as_ref() {
                        !matches!(self.get_var_type(v), TypeAnnotation::Dynamic)
                    } else {
                        false
                    }
                } else {
                    false
                };

                let right_is_static = if let Expr::Var(v) = right.as_ref() {
                    !matches!(self.get_var_type(v), TypeAnnotation::Dynamic)
                } else if let Expr::FieldAccess { object, .. } = right.as_ref() {
                    if let Expr::Var(v) = object.as_ref() {
                        !matches!(self.get_var_type(v), TypeAnnotation::Dynamic)
                    } else {
                        false
                    }
                } else {
                    false
                };

                if left_is_static && right_is_static {
                    let l = self.gen_expr(left, false);
                    let r = self.gen_expr(right, false);
                    let op_str = match op {
                        BinaryOp::Add => "+",
                        BinaryOp::Sub => "-",
                        BinaryOp::Mul => "*",
                        BinaryOp::Div => "/",
                        BinaryOp::Mod => "%",
                        BinaryOp::Eq => "==",
                        BinaryOp::NotEq => "!=",
                        BinaryOp::Lt => "<",
                        BinaryOp::Gt => ">",
                        BinaryOp::LtEq => "<=",
                        BinaryOp::GtEq => ">=",
                        BinaryOp::And => "&&",
                        BinaryOp::Or => "||",
                    };
                    return format!("({} {} {})", l, op_str, r);
                }

                let l = self.gen_expr(left, true);
                let r = self.gen_expr(right, true);

                let l_wrapped = if left_is_static {
                    let raw_l = self.gen_expr(left, false);
                    format!("Value::Str(({}).to_string())", raw_l)
                } else {
                    l
                };

                let r_wrapped = if right_is_static {
                    let raw_r = self.gen_expr(right, false);
                    format!("Value::Str(({}).to_string())", raw_r)
                } else {
                    r
                };

                match op {
                    BinaryOp::Add => format!("({} + {})", l_wrapped, r_wrapped),
                    BinaryOp::Sub => format!("({} - {})", l_wrapped, r_wrapped),
                    BinaryOp::Mul => format!("({} * {})", l_wrapped, r_wrapped),
                    BinaryOp::Div => format!("({} / {})", l_wrapped, r_wrapped),
                    BinaryOp::Mod => format!("({} % {})", l_wrapped, r_wrapped),
                    BinaryOp::Eq => format!("Value::Bool({} == {})", l_wrapped, r_wrapped),
                    BinaryOp::NotEq => format!("Value::Bool({} != {})", l_wrapped, r_wrapped),
                    BinaryOp::Lt => format!("Value::Bool({} < {})", l_wrapped, r_wrapped),
                    BinaryOp::Gt => format!("Value::Bool({} > {})", l_wrapped, r_wrapped),
                    BinaryOp::LtEq => format!("Value::Bool({} <= {})", l_wrapped, r_wrapped),
                    BinaryOp::GtEq => format!("Value::Bool({} >= {})", l_wrapped, r_wrapped),
                    BinaryOp::And => format!("Value::Bool(({}).is_truthy() && ({}).is_truthy())", l_wrapped, r_wrapped),
                    BinaryOp::Or => format!("Value::Bool(({}).is_truthy() || ({}).is_truthy())", l_wrapped, r_wrapped),
                }
            }

            Expr::Unary { op, expr } => {
                let e = self.gen_expr(expr, true);
                match op {
                    UnaryOp::Not => format!("Value::Bool(!({}).is_truthy())", e),
                    UnaryOp::Neg => format!("(-{})", e),
                }
            }

            Expr::Call { callee, args } => {
                if let Expr::Var(fn_name) = callee.as_ref() {
                    if fn_name == "print" || fn_name == "println" {
                        let arg_strs: Vec<String> = args
                            .iter()
                            .map(|a| {
                                if let Expr::Var(v) = a {
                                    let ty = self.get_var_type(v);
                                    if !matches!(ty, TypeAnnotation::Dynamic) {
                                        return format!("&Value::Str({}.to_string())", v);
                                    }
                                }
                                let expr_str = self.gen_expr(a, true);
                                if expr_str.starts_with("Value::") || expr_str.contains(".clone()") {
                                    format!("&{}", expr_str)
                                } else {
                                    format!("&Value::Str(({}).to_string())", expr_str)
                                }
                            })
                            .collect();
                        let func_name = if fn_name == "print" { "lingo_print" } else { "lingo_println" };
                        return format!("{}({})", func_name, arg_strs.join(", "));
                    }
                }

                if let Expr::FieldAccess { object, field } = callee.as_ref() {
                    let arg_strs: Vec<String> = args.iter().map(|a| self.gen_expr(a, false)).collect();
                    if let Expr::Var(ref obj_name) = object.as_ref() {
                        if obj_name.chars().next().map_or(false, |c| c.is_uppercase()) {
                            return format!("{}::{}({})", obj_name, field, arg_strs.join(", "));
                        }
                    }
                    let obj_str = self.gen_expr(object, false);
                    return format!("{}.{}({})", obj_str, field, arg_strs.join(", "));
                }

                let callee_str = self.gen_expr(callee, false);
                let arg_strs: Vec<String> =
                    args.iter().map(|a| self.gen_expr(a, false)).collect();
                format!("{}({})", callee_str, arg_strs.join(", "))
            }

            Expr::FieldAccess { object, field } => {
                if let Expr::Var(ref var_name) = object.as_ref() {
                    let ty = self.get_var_type(var_name);
                    if matches!(ty, TypeAnnotation::Named(_)) {
                        return format!("{}.{}", var_name, field);
                    }
                }

                let obj_str = self.gen_expr(object, false);
                format!("{}.get_field({:?})", obj_str, field)
            }

            Expr::IndexAccess { object, index } => {
                let obj_str = self.gen_expr(object, false);
                let idx_str = self.gen_expr(index, true);
                format!("{}.get_index(&{})", obj_str, idx_str)
            }

            Expr::Borrow { mutable, expr } => {
                let mut_kw = if *mutable { "mut " } else { "" };
                let e = self.gen_expr(expr, false);
                format!("&{}{}", mut_kw, e)
            }

            Expr::List(elements) => {
                let elem_strs: Vec<String> =
                    elements.iter().map(|e| self.gen_expr(e, true)).collect();
                format!(
                    "Value::List(std::rc::Rc::new(std::cell::RefCell::new(vec![{}])))",
                    elem_strs.join(", ")
                )
            }

            Expr::Map(pairs) => {
                let mut s = String::from("Value::Map(std::rc::Rc::new(std::cell::RefCell::new({\nlet mut m = std::collections::HashMap::new();\n");
                for (k, v) in pairs {
                    let k_str = self.gen_expr(k, false);
                    let v_str = self.gen_expr(v, true);
                    s.push_str(&format!("m.insert({}.to_string(), {});\n", k_str, v_str));
                }
                s.push_str("m\n})))");
                s
            }

            Expr::StructInit { name, fields } => {
                let field_strs: Vec<String> = fields
                    .iter()
                    .map(|(f, v)| format!("{}: {}", f, self.gen_expr(v, false)))
                    .collect();
                format!("{} {{ {} }}", name, field_strs.join(", "))
            }
        }
    }
}
